config/routes.rb
Proudawear::Application.routes.draw do

  get "votes/create"

  get "votes/new"

  get "votes/edit"

  get "votes/delete"

  resources :posts do 
    resources :reviews
    resources :votes
    member do
      post :upvote
      post :downvote
    end
  end

  resources :users, path: 'fashionistas'

  post '/reviews' => 'review#create'

  root :to => "posts#index"

  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider/callback' => 'Users#create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :description, :name, :uid, :image, :nickname
  validates_presence_of :name
  has_many :reviews
  has_many :posts
  has_one :votes

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

  #Below tries to find an existing user by uid or create one with a random password otherwise.
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    puts "OAUTH: #{auth}"
    @user = User.where(:provider => auth.provider, :uid => auth.uid).first
    return @user if @user
    @user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           nickname:auth.info.nickname,
                           image:auth.info.image,
                           email:auth.info.email,
                           # image: auth.info.secure_image_url,
                           password:Devise.friendly_token[0,20]
                           )


    # ***** Code that was breaking before but sort of working, keeping just in case:
    # unless @user
    #   @user = User.create(name:auth.extra.raw_info.name,
    #                        provider:auth.provider,
    #                        uid:auth.uid,
    #                        nickname:auth.info.nickname,
    #                        image:auth.info.image,
    #                        email:auth.info.email,
    #                        # image: auth.info.secure_image_url,
    #                        password:Devise.friendly_token[0,20]
    #                        )
    # else 
    #   @user = User.where(:provider => auth.provider, :uid => auth.uid).first
    # end

    #add image
    # if auth.info.image.present?
    #   @user.update_attribute(:image, auth.info.image)
    # end
    
    return @user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["user_hash"]
        user.email = data["email"]
      end
    end
  end
  


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    #here, we're getting back the callback for authentication
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    # with this code you can see the data sent by facebook
    omniauth = request.env["omniauth.auth"] 

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to request.referrer

    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessible :provider, :uid, :name
  before_filter :authenticate_user!, :correct_user?, :except => [:index]

 

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!-- <h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Picture</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.picture %></td>
    <td><%= user.description %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show-01.html.erb
<!--Users show view as a table -->
<p id="notice"><%= notice %></p>

<!-- Checks that user is logged in -->
<% if current_user == @user %>
	<h1> Post History </h1>


	

	<div class="table">
	<table>
	  <tr>
	    <th>Picture</th>
	    <th>Title</th>
	    <th>Description</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	<br>

	<% Post.all.each do |post| %>  
		<% if post.name == @user.name && @user.name == current_user.name %>
		  <tr>    
		    <% if post.picture.present? %>
		        <td><%= image_tag post.picture, width: '60'%></td>
		    <% else %>
		        <td>N/A</td>
		    <% end %>
		    <td><%= post.title %></td>
		    <td><%= post.description %></td>
		    <td><%= link_to 'Show', post %></td>
		    <td><%= link_to 'Edit', edit_post_path(post) %></td>
		    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
	<% end %>
	</table>
	</div>

	<%= link_to 'Home', posts_path %>
<% else %>
	<p> You must be logged in as this user to view profile </p>
<% end %>

<!-- Taken from posts/index view-->

app/views/users/show.html.erb
<!-- Users show view a with masonry -->
<p id="notice"><%= notice %></p>

<div class='container users'>
<!-- Checks that user is logged in -->
  <% if current_user == @user %>
  	

    <div class="post_container_wrapper users">
      <center>
      <div class="info_container users">
        <h1> <%= current_user.name %>'s Post History </h1>
        
      </div>
        <center>
        <div id="container" class="js-masonry centered photos clearfix users" data-masonry-options='{ "columnWidth": 0, "itemSelector": ".item", "gutter": 3 }'>
          <center>
          <% Post.all.sort.reverse.each do |post| %>  
            <% if post.name == @user.name && @user.name == current_user.name %>
              <div class= "box item photo centered">
                <%= link_to image_tag(post.picture_url), post %>
              </div>
            <% end %>
          <% end %>
          </center>
        </div>
        </center>
      </div>
      </center>
    </div>
    <!-- Formats the images so they recenter when screen size changes (Code borrowed from 'posts/index' view) -->
    <!-- Link to Home -->
  <% else %>
  	<p> You must be logged in as this user to view profile </p>
  <% end %>

</div>