config/routes.rb
Proudawear::Application.routes.draw do

  get "votes/create"

  get "votes/new"

  get "votes/edit"

  get "votes/delete"

  resources :posts do 
    resources :reviews
    resources :votes
    member do
      post :upvote
      post :downvote
    end
  end

  resources :users, path: 'fashionistas'

  post '/reviews' => 'review#create'

  root :to => "posts#index"

  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider/callback' => 'Users#create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

 

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :post, :rating, :user
  belongs_to :user
  belongs_to :post

  # validates_uniqueness_of :user_id, :scope => [:post_id, :rating]
  #validates :user_id, :uniqueness => true
#make sure to changes validates, the validates makes it 
#validate against all votes
  
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = Vote.create(params[:vote], user_id: current_user.id, post_id: @post.id)

  end

  def destroy
    @vote =Vote.find(user_id: current_user.id, post_id: @post.id).destroy
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end




end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_formdownvote.html.erb
<%= form_for [@post, @vote], :url => downvote_post_path(@post) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <%= image_submit_tag('mannequin-crossed.png', class: 'button downvoting') %>
  

<% end %>

app/views/votes/_formupvote.html.erb
<%= form_for [@post, @vote], :url => upvote_post_path(@post) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= image_submit_tag('mannequin-checked.png', class: 'button upvoting') %>
  

<% end %>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/delete.html.erb
<h1>Votes#delete</h1>
<p>Find me in app/views/votes/delete.html.erb</p>

app/views/votes/edit.html.erb
<h1>Votes#edit</h1>
<p>Find me in app/views/votes/edit.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>