config/routes.rb
Proudawear::Application.routes.draw do

  get "votes/create"

  get "votes/new"

  get "votes/edit"

  get "votes/delete"

  resources :posts do 
    resources :reviews
    resources :votes
    member do
      post :upvote
      post :downvote
    end
  end

  resources :users, path: 'fashionistas'

  post '/reviews' => 'review#create'

  root :to => "posts#index"

  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider/callback' => 'Users#create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- i had to install bower as well as classie look up documentation on that for questions
 -->
<html>
<head>

	<meta charset = "utf-8" />
  <!-- Set the viewport width to device width for mobile -->

  
<!--   Set the viewport width to device width for mobile
 -->  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!--   >Includes all the js files assets/stylesheets</!
 -->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

<!--   >The csrf_meta_tag inserts what is essentially a digitial signature into the page. It acts as a verification that the requests coming into the application server are from properly logged in users</!
 -->  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Michroma|Actor' rel='stylesheet' type='text/css'>



  
  <title>proudawear</title>
  
<!--  // <script src="http://masonry.desandro.com/masonry.pkgd.min.js"></script> -->


</head>

<body>

<header>
	<div class="fixed sticky">
		<nav class="top-bar" data-options="is_hover:false">
			<ul class="title-area">
				<li class="name">
				<h3 class = "proudawear_title"><%= link_to 'proudawear', posts_path, id: 'proudawear' %></h3>
				</li>
				<li class="toggle-topbar menu-icon" id= "menu_dropdown"><a href="#" id="menu"><span></span></a></li>
<!-- 				Look up breakpoints for Foundation -->
			</ul>
			<section class="top-bar-section">
				
				<% if current_user %>
					<ul class="right logged_in">	
						<li>
							<%= image_tag current_user.image, width: '30', class: "user_photo" %> 
						</li>
						<li class = "has-dropdown">
							<%= link_to "Logged in as #{current_user.name}", '#', id: "user_name" %>

							<ul class="dropdown">
								<li><%= link_to 'My Previous Posts', User.find(current_user.id) %>
								</li>
								<li>
									<%= link_to 'Logout', signout_path, :class => 'view_logout' %>
								</li>
							</ul>
						</li>

					</ul>

				<% else %>
					<ul class="right login_ul">
						<li>
							
							<%= link_to image_tag('Facebook_login.png', class: "facebook_login"), user_omniauth_authorize_path(:facebook), id: "fb_login" %>			
						</li>
					</ul>
				<% end %>
			</section>
		</nav>
	</div>

</header>


<%= yield %>

<div id="footer">
	<% if current_user %>
	<center><%= link_to image_tag('mirror.jpg', class: 'mirror'), new_post_path, class: "button", id:"mirror_button" %></center>
	<% end %>

</div>

	<%= javascript_include_tag "application" %>

</body>
</html>